#!/bin/sh

if [ -z "${STAGING_PREFIX}" ]; then
	exec /usr/bin/pkg-config "$@"
else
	exec pkg-config.real "$@" --define-variable=prefix=${STAGING_PREFIX} --define-variable=exec_prefix=${STAGING_PREFIX}
fi
